#!/usr/bin/env python3
"""make_calc_data.py - the options table for the model calculator, as a separate file.

  Author: Carles Marin <karlesmarin@gmail.com>  (with Claude, Anthropic, as assistant)

The page is the instrument; this is its catalogue, and it lives apart from it on purpose. Every row
is computed from the VERIFIED characters of Part V -- `fibre.schur` on the two alphabets -- and not
from any hand-kept list:

    Sigma_lambda = s_lambda(1, 1,t,1/t)   the identity component, a graded dimension
    D_lambda     = s_lambda(1,-1,t,1/t)   the reflection coset,   an index

Per irrep, keyed by the Dynkin labels (a,b,c) so the page can look one up from the labels alone:

    dim     the dimension, as the sum of the mode counts (a free control: it must come out right)
    modes   [charge, A, B] with A = (Sigma+D)/2 and B = (Sigma-D)/2, the parity-even and
            parity-odd mode counts -- exactly the pair AHMN write as {A + B(-1)^k2}
    blind   D vanishes identically: the boundary sign is invisible on this multiplet (Part V)
    sides   the three SU(2) character indices of Part IV's closed form, read off the 2-quotient
    zeta    its global sign

`blind` is computed twice by different routes -- the character being empty, and the closed
criterion on the partition -- and the two must agree on every row or this script fails. A
catalogue that disagrees with the theorem it illustrates is worse than no catalogue.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from fibre import schur, EVEN, ODD

MAXSUM = int(os.environ.get("CALC_MAXSUM", 7))     # a+b+c <= 7, as the Part III explorer uses
MAXDIM = int(os.environ.get("CALC_MAXDIM", 3000))


def lam_of(a, b, c):
    return [a + b + c, b + c, c, 0]


def blind_by_criterion(lam):
    """Proposition 1 of Part V, in partition coordinates -- the machine-checked branches."""
    l1, l2, l3, _ = lam
    return (l1 % 2 == 1 and l2 % 2 == 0 and l3 % 2 == 1) or \
           (l1 % 2 == 1 and l2 % 2 == 1 and l3 % 2 == 0 and l2 + l3 == l1)


def sides(lam):
    """The three SU(2) indices of Part IV's box, from the 2-quotient of the beta set."""
    beta = [lam[0] + 3, lam[1] + 2, lam[2] + 1, lam[3]]
    ev = sorted([b // 2 for b in beta if b % 2 == 0], reverse=True)
    od = sorted([b // 2 for b in beta if b % 2 == 1], reverse=True)
    if not ev or not od:
        return None
    if len(ev) == 2:                      # the 2+2 profile
        z = (sum(ev) - sum(od)) - 1
        return sorted([ev[0] - ev[1], od[0] - od[1], abs(z) - 1], reverse=True)
    nu = ev if len(ev) == 3 else od       # the 3+1 profile
    return sorted([nu[0] - nu[1], nu[1] - nu[2], nu[0] - nu[2] + 1], reverse=True)


def main():
    reps, bad = {}, []
    for a in range(MAXSUM + 1):
        for b in range(MAXSUM + 1 - a):
            for c in range(MAXSUM + 1 - a - b):
                lam = lam_of(a, b, c)
                S, D = schur(lam, EVEN), schur(lam, ODD)
                modes = []
                dim = 0
                for j in sorted(set(S) | set(D)):
                    s, d = S.get(j, 0), D.get(j, 0)
                    A, B = (s + d) // 2, (s - d) // 2
                    dim += A + B
                    if j > 0:
                        modes.append([j / 2.0, A, B])
                if dim > MAXDIM or dim == 0:
                    continue
                blind = not any(v for v in D.values())
                if blind != blind_by_criterion(lam):
                    bad.append("(%d,%d,%d): character says %s, criterion says %s"
                               % (a, b, c, blind, blind_by_criterion(lam)))
                reps["%d,%d,%d" % (a, b, c)] = {
                    "dim": dim, "modes": modes, "blind": blind,
                    "sides": None if blind else sides(lam),
                    "zeta": 0 if blind else (1 if max(D.items())[1] > 0 else -1),
                }
    if bad:
        sys.exit("FATAL: catalogue disagrees with Proposition 1 on %d rows:\n  %s"
                 % (len(bad), "\n  ".join(bad[:5])))
    out = {
        "note": "Part V options table. modes = [charge, A, B]; A+B(-1)^k2 is AHMN's coefficient. "
                "blind = the boundary sign is invisible on this multiplet (Part V, Lean-checked). "
                "Generated by make_calc_data.py from the verified characters; do not hand-edit.",
        "maxsum": MAXSUM, "maxdim": MAXDIM,
        "adjoint": "1,1,0" if "1,1,0" in reps else None,
        "reps": reps,
    }
    p = os.path.join(os.path.dirname(os.path.abspath(__file__)), "calc_data.json")
    with open(p, "w", encoding="utf-8") as fh:
        json.dump(out, fh, separators=(",", ":"), sort_keys=True)
    nb = sum(1 for r in reps.values() if r["blind"])
    print("%d irreps (a+b+c <= %d, dim <= %d), %d blind, %d sighted"
          % (len(reps), MAXSUM, MAXDIM, nb, len(reps) - nb))
    print("catalogue agrees with Proposition 1 on every row")
    print("written: %s (%d bytes)" % (p, os.path.getsize(p)))


if __name__ == "__main__":
    main()
